trustification/exhort-javascript-api

.github/workflows/pr.yml
.github/workflows/stage.yml

ci: added initial ci workflows

---

.github/auto-me-bot.yml

ci: added auto-me-bot configuration

---

package-lock.json
package.json
src/cmd.js
src/index.js
src/provider.js
test/providers/java_maven.test.js

chore: added cmd script for npm x / npx

---

.gitignore
integration/expected_component
integration/run_it.sh
package-lock.json
src/cli.js
src/providers/java_maven.js
test/providers/java_maven.test.js
test/providers/tst_manifests/pom_deps_with_ignore_on_artifact/component_expected_list
test/providers/tst_manifests/pom_deps_with_ignore_on_dependency/component_expected_list
test/providers/tst_manifests/pom_deps_with_ignore_on_group/component_expected_list
test/providers/tst_manifests/pom_deps_with_ignore_on_version/component_expected_list
test/providers/tst_manifests/pom_deps_with_ignore_on_wrong/component_expected_list
test/providers/tst_manifests/pom_deps_with_no_ignore/component_expected_list
test/providers/tst_manifests/pom_empty/pom.xml

chore: added component analysis

---

.github/workflows/stage.yml

ci: fixed release workflow

---

package-lock.json
package.json

ci: added missing package for publishing

---

.github/workflows/stage.yml

ci: final fix for staging workflow

---

src/cli.js

fix: missing shebang from cli script

---

CONTRIBUTING.md
README.md

- docs: update README
- docs: added contribution guidelines

docs: update readme and contributing

---

CONTRIBUTING.md
README.md

docs: fixed typos

---

README.md

docs: update readme with package exclusion section

---

.github/workflows/stage.yml

ci: reveresd staging ci trigger, will only trigger for source-related files

---

CONTRIBUTING.md
README.md
src/analysis.js
src/index.js
test/analysis.test.js

- chore: added mechinsm for including token from env vars as request headers
- chore: added option to replace backend url with an evn var

chore: added env vars for token and backend

---

README.md

docs: update typos in readme

---

README.md
src/providers/java_maven.js

chore: add option for setting custom mvn path using env var

---

.github/workflows/stage.yml

ci: prevent staging workflow from running on forks

---

integration/scenarios/maven/expected_component
integration/scenarios/maven/expected_stack_html
integration/scenarios/maven/expected_stack_json
integration/scenarios/maven/expected_stack_json_summary

introduced in https://github.com/RHEcosystemAppEng/crda-backend/pull/66

chore: update scnarions testing files

---

README.md
src/analysis.js
src/index.js
src/provider.js
src/providers/java_maven.js
src/tools.js
test/analysis.test.js
test/providers/java_maven.test.js
test/tools.test.js

- chore: added utility function for fetching various custom values
- chore: pass opts through out the application
- chore: added utility function for fetching custom paths
- docs: update docs with new options feature

feat: customizing programtically

---

.github/workflows/oapi_spec.yaml

ci: added workflow verifying openapi spec generation

---

integration/run_its.sh
src/cli.js
src/providers/java_maven.js
test/providers/java_maven.test.js
test/providers/tst_manifests/pom_deps_with_ignore_on_artifact/component_expected_list
test/providers/tst_manifests/pom_deps_with_ignore_on_dependency/component_expected_list
test/providers/tst_manifests/pom_deps_with_ignore_on_group/component_expected_list
test/providers/tst_manifests/pom_deps_with_ignore_on_version/component_expected_list

fix: component analysis fails to ignore dependencies

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
README.md
integration/run_its.sh
integration/scenarios/maven/expected_stack_html
integration/testers/cli/package.json
integration/testers/javascript/index.js
integration/testers/javascript/package.json
integration/testers/typescript/index.ts
integration/testers/typescript/package.json
package-lock.json
package.json
src/analysis.js
src/cli.js
src/index.js
src/providers/java_maven.js
src/tools.js
test/analysis.test.js
test/providers/tst_manifests/pom_deps_with_ignore_on_artifact/pom.xml
test/providers/tst_manifests/pom_deps_with_ignore_on_dependency/pom.xml
test/providers/tst_manifests/pom_deps_with_ignore_on_group/pom.xml
test/providers/tst_manifests/pom_deps_with_ignore_on_version/pom.xml
test/providers/tst_manifests/pom_deps_with_ignore_on_wrong/pom.xml
test/tools.test.js

- Rename project and packages to Exhort.
- Rename headers and environment variables
- Adapt to updated openapi location
- https://issues.redhat.com/browse/APPENG-1889
- https://github.com/RHEcosystemAppEng/exhort/pull/76

refactor: rename to exhort

---

src/index.js

- Change the default Backend Route address to http://dev-exhort.apps.sssc-cl01.appeng.rhecoeng.com

chore: change default backend url

---

src/index.js

refactor: change back-end default route  to single source (single vendor)  version

refactor: change backend default route 

---

.github/workflows/stage.yml
docker-image/Dockerfiles/Dockerfile
docker-image/Dockerfiles/Dockerfile.alpha
docker-image/README.md
docker-image/configs/.npmrc
docker-image/scripts/exhort.sh
integration/run_its.sh

chore: add docker image for exhort alpha

---

docker-image/README.md
docker-image/scripts/exhort.sh

chore: print stderr to console

---

.github/workflows/stage.yml

add context path to build image with buildah step

fix: add context to workflow buildah action

---

integration/run_its.sh
package.json
src/analysis.js
src/index.js
src/tools.js
tsconfig.json

https://issues.redhat.com/browse/APPENG-2000
Enable attaching rhda-token header to request send to exhort backend,  if exists as environment variable / (key,value) in `options/opts` javascript object

feat: attach to request rhda-token if exists in env/option

---

src/providers/python_pip.js

fix: opts object is not propagated to python controller

---

package-lock.json
package.json
src/providers/golang_gomodules.js
test/providers/test-utils.js

fix: fix opts in go and vulns

---

src/providers/python_controller.js

including infrastructural ones ( like setuptools, wheels, etc).
Need to take into account all python packages from environment, including infrastructural ones ( like setuptools, wheels, etc).

fix: need to consider all python packages

---

catalog-info.yaml

feat: adding initial backstage configuration version

---

src/analysis.js
src/index.js
src/providers/java_maven.js
test/providers/tst_manifests/maven/pom_deps_with_no_ignore_common_paths/component_analysis_expected_sbom.json
test/providers/tst_manifests/maven/poms_deps_with_2_ignore_long/component_analysis_expected_sbom.json
test/providers/tst_manifests/maven/poms_deps_with_ignore_long/component_analysis_expected_sbom.json
test/providers/tst_manifests/maven/poms_deps_with_no_ignore_long/component_analysis_expected_sbom.json

fix:  maven - only add artifact to sbom if it's not test scoped in pom.xml manifest
refactor: change default URL for Exhort
feat: oss-index - add header and mapping from setting/envVar

fix: maven - exclude test artifacts

---

.github/workflows/release.yml

ci: fix syntax error in workflow

---

.github/workflows/release.yml

ci: final fixes and adjustments for release workflow

---

package.json
src/providers/java_maven.js

fix: in case version is of type `number` , "stringify" it

---

src/analysis.js
test/it/end-to-end.js

feat: log ex-request-id resp header in debug Mode

---

openapitools.json
src/analysis.js
test/it/end-to-end.js

chore: test workflow

---

package-lock.json
src/analysis.js
src/providers/python_controller.js
src/providers/python_pip.js
src/tools.js
test/it/end-to-end.js

fix: skip binaries validation when externalizing pip commands

---

docker-image/Dockerfiles/Dockerfile

ci: fix broken link of JDK in Dockerfile

---

.github/workflows/pr.yml
integration/run_its.sh
package-lock.json
package.json
src/cli.js
test/it/end-to-end.js

feat: expose validate token for cli usage
test: add integration test for CLI
ci: add step for integration test cli

feat: expose validate token for cli usage

---

.github/workflows/pr.yml
src/providers/golang_gomodules.js
test/it/end-to-end.js
test/providers/golang_gomodules.test.js
test/providers/tst_manifests/golang/go_mod_mvs_versions/expected_sbom_stack_analysis.json
test/providers/tst_manifests/golang/go_mod_mvs_versions/go.mod
test/providers/tst_manifests/golang/go_mod_with_all_ignore/expected_sbom_component_analysis.json
test/providers/tst_manifests/golang/go_mod_with_all_ignore/expected_sbom_stack_analysis.json
test/providers/tst_manifests/golang/go_mod_with_all_ignore/go.mod

Same concept and similar Algorithms as in exhort-java-api lib' [PR#86](https://github.com/RHEcosystemAppEng/exhort-java-api/pull/86)
Jira Ticket [APPENG-2170](https://issues.redhat.com/browse/APPENG-2170)

feat: add functionallity of EXHORT_GO_MVS_LOGIC_ENABLED setting

---

integration/run_its.sh

test: add cli test for stack analysis summary option

---

.github/workflows/stage.yml

ci: prevent staging wf from running twice

---

docker-image/Dockerfiles/Dockerfile

Parameterize java 21' minor and patch components in Dockerfile, in order to fix broken multi stage build, and in order to ease bumping the minor and patch components much easier whenever needed.

fix: parameterize Dockerfile' jdk minor+patch version

---

docker-image/Dockerfiles/Dockerfile

docs: add comment

---

.github/workflows/stage.yml
docker-image/Dockerfiles/Dockerfile

ci: trigger staging pipeline for docker image change

---

docker-image/Dockerfiles/Dockerfile

fix: replace placeholder with secret token

---

.github/workflows/stage.yml
package-lock.json
package.json

ci: stage from forks

---

.github/workflows/stage.yml

ci: remove main branch condition from pull_request

---

.github/workflows/stage.yml

ci: stage release from forks with fixes

---

.github/workflows/stage.yml
README.md
package.json

ci: trigger staging only for main branch in PR

---

.github/workflows/stage.yml
package.json

ci: allow forks to stage 

---

.github/workflows/stage.yml

ci: enable forks repo to stage via PR

---

.github/workflows/stage.yml

ci: fix event name

---

src/providers/javascript_npm.js
src/providers/python_controller.js

Fixes: [JIRA-2316](https://issues.redhat.com/browse/APPENG-2316)

feat: allow manifest from path for npm CA

---

src/providers/python_controller.js
test/it/end-to-end.js

fix: bug of parsing package without version in requirements.txt

---

test/it/end-to-end.js

Remove Snyk Provider from integration tests.
Was done due to [Decommission of Snyk](https://issues.redhat.com/browse/APPENG-2344)

test: remove snyk provider from integration tests

---

integration/run_its.sh
package.json
src/providers/python_pip.js
test/it/end-to-end.js
test/providers/python_pip.test.js
test/providers/tst_manifests/pip/pip_requirements_txt_ignore/expected_component_sbom.json
test/providers/tst_manifests/pip/pip_requirements_txt_ignore/expected_stack_sbom.json
test/providers/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_component_sbom.json
test/providers/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_stack_sbom.json
test/providers/tst_manifests/pip/pip_requirements_virtual_env_txt_no_ignore/expected_stack_sbom.json
test/providers/tst_manifests/pip/pip_requirements_virtual_env_with_ignore/expected_stack_sbom.json

Fixes Jira [TC-664](https://issues.redhat.com/browse/TC-664)

fix: revive root component in generated sbom for python pip

---

src/providers/java_gradle.js

fix: gradle ca produces two versions of the same package

---

.github/workflows/stage.yml

ci: fix workflow error because of python action location

---

.github/workflows/stage.yml
package-lock.json
package.json

1. fix: get newer cyclonedx version without vuln
2.  ci: fix workflow print typo

fix: get newer cyclonedx version without vuln

---

src/index.js

fix: print version of api only in case of EXHORT_DEBUG=true

---

src/analysis.js
src/providers/golang_gomodules.js

fix: in windows os, golang creates output with newlines of linux anyway

---

.github/PULL_REQUEST_TEMPLATE.md
.github/auto-me-bot.yml
.github/workflows/pr.yml
package-lock.json

I ran the npm audit fix command to update the 6 high and 3 moderate vulnerabilities leaving only 2 low

chore: update deps with audit-fix command

---

.github/workflows/pr-validation.yml
.github/workflows/pr.yml

Validate commit and title messages
**Related issues (if any):**

build: validate commit and title messages

---

.github/auto-me-bot.yml

Restore check for signedCommits
Revert https://github.com/RHEcosystemAppEng/exhort-javascript-api/pull/153

build: restore signedCommits check

---

.github/auto-me-bot.yml

build: remove autome bot

---

docker-image/configs/.npmrc

chore: revert to RHEcosystemAppEng in .npmrc for building docker image

---

src/providers/golang_gomodules.js
test/providers/golang_gomodules.test.js

**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/163

fix: correctly return custom golang invocation error messages

---

src/tools.js

A regression introduced when moving to `execFileSync` that wasnt caught as we didnt test on windows. `execFileSync` by default can't run `.cmd` or `.bat` files on windows without `{shell: true}`, so we would hand off to `execSync` instead as previously done. However this doesnt work when we dont include `.cmd` or `.bat` in the file to be executed e.g. when we pass `npm`, it would attempt to `execFileSync` it on the non-shell path which doesnt work even though it is executing a `.cmd` file (under the hood Windows attempts a few file extensions, see details here: https://superuser.com/a/1351814). To address this, Ive changed it to always pass `{shell: true}` on the windows platform, using `execFileSync` with all args etc sanitized for spaces.
- fixes: TODO create issue

fix: fix invoking of binaries on windows

---

README.md
src/providers/base_java.js
src/providers/java_gradle.js
src/providers/java_maven.js
test/it/end-to-end.js

- fixes: #169
Also updates e2e tests to use tpa responses instead of the no longer existing osv ones

feat: support preferring gradlew

---

package-lock.json
package.json

- fixes: #issue_number_goes_here

chore(deps): use exhort-api-spec@1.0.13

---

package-lock.json
package.json
src/analysis.js

The previous approach for adding a proxy was not working as expected.
- fixes: #196 

fix: use http-proxy-agent

---

src/analysis.js
src/index.js

Parameters werent being passed properly, so opts object was passed as the html flag

fix: pass html flag correctly to image analysis

---

src/oci_image/utils.js

chore: check for ENOENT in docker/podman/syft & skopeo

---

src/providers/base_java.js
src/providers/java_maven.js

- fixes: https://github.com/trustification/exhort-javascript-api/issues/212

fix: set cwd for mvn invocations to manifest dir

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Updated the templates to use `type` instead of `label`
Updated the reference in the `contact_links` to point to the right discussions page

chore(ci): update templates and config

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

chore(ci): update template types and labels

---

README.md
src/analysis.js
src/index.js
tsconfig.json

Follow up on https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/795

feat: support toggling of recommendations
