trustification/exhort-javascript-api

- .github/workflows/stage.yml
- integration/run_its.sh
> chore: prepare for first early-access release

- src/analysis.js
- src/index.js
- src/providers/java_maven.js
- test/analysis.test.js
- test/providers/java_maven.test.js
fix: fix maven artifacts' versions sometimes interpreted as integer instead of string
-  Add new function validateToken to let clients check providers' tokens , instead of calling backend directly
- Fix bug of sometimes maven artifacts' version are interpreted as numbers/integers instead of  string.
> feat: add new function validateToken to check providers tokens

- src/cyclone_dx_sbom.js
- test/providers/tst_manifests/golang/go_mod_with_ignore/expected_sbom_stack_analysis.json
fix: purl of components in sbom sometimes shows [Object Object] instead of expected package url formatted string
> fix: purl of components in sbom sometimes shows [Object Object]

- src/providers/javascript_npm.js
Always re-create the package-lock.json because after the user updates the package.json file, the extension will run another analysis and it will fail because the package-lock.json is not synchronized.
- [TC-529](https://issues.redhat.com/browse/TC-529)
> fix: always re-create package-lock.json

- src/providers/java_maven.js
- test/providers/java_maven.test.js
- test/providers/tst_manifests/maven/pom_deps_with_no_ignore_common_paths/component_analysis_expected_sbom.json
- test/providers/tst_manifests/maven/pom_deps_with_no_ignore_common_paths/pom.xml
- test/providers/tst_manifests/maven/pom_deps_with_no_ignore_common_paths/stack_analysis_expected_sbom.json
- test/providers/tst_manifests/maven/poms_deps_with_2_ignore_long/stack_analysis_expected_sbom.json
- test/providers/tst_manifests/maven/poms_deps_with_ignore_long/stack_analysis_expected_sbom.json
- test/providers/tst_manifests/maven/poms_deps_with_no_ignore_long/stack_analysis_expected_sbom.json
The `dependency:tree` plugin omits duplicates but when using the `verbose` flag the omitted are shown. However the plugin only yields the `text` type in that case.
I have added the `verbose` flag to the `mvn dependency:tree` command and changed how the text file is processed with the `text` format.
**Related issue (if any):** 
fixes #44 
Related to https://github.com/RHEcosystemAppEng/exhort/pull/135
> fix: missing common maven transitive dependencies

- src/index.js
- test/providers/golang_gomodules.test.js
This is very useful feature but a package ( get-root-path ) that it's relying on doing some problems for what concerns dependency management and resolution on client Vscode Extension at build time  , probably because it's pretty old dependency.
So i'm dropping this nice to have feature.
> fix: drop bundled config file

- docker-image/scripts/exhort.sh
substituted --argjson with --slurpfile in order to deal with large Json objects and overcome the "Argument list too long" error when writing report result to file.
> fix: argument list too long error when writing json report to file

- src/providers/javascript_npm.js
- test/providers/tst_manifests/npm/package_json_deps_with_exhortignore_object/component_expected_sbom.json
- test/providers/tst_manifests/npm/package_json_deps_with_exhortignore_object/package-lock.json
- test/providers/tst_manifests/npm/package_json_deps_with_exhortignore_object/package.json
- test/providers/tst_manifests/npm/package_json_deps_with_exhortignore_object/stack_expected_sbom.json
Ignore optional dependencies.
**Related issue (if any):** fixes #54
> fix: ignore optional non resolved dependencies

- src/cyclone_dx_sbom.js
- src/providers/golang_gomodules.js
- src/sbom.js
- test/providers/golang_gomodules.test.js
- test/providers/tst_manifests/golang/go_mod_with_all_ignore/expected_sbom_component_analysis.json
- test/providers/tst_manifests/golang/go_mod_with_all_ignore/expected_sbom_stack_analysis.json
- test/providers/tst_manifests/golang/go_mod_with_all_ignore/go.mod
- test/providers/tst_manifests/golang/go_mod_with_ignore/expected_sbom_stack_analysis.json
fix: exhortignored not respected for couple of edge cases regex that should capture all cases of packages names + versions in go.mod
fix: in case of automatic version bump, the exhortignored package wrongly shown as a direct dependency in generated sbom
fix: filter the exhortignored packages after sbom creation instead of during creation
test: add new test that all direct dependencies are ignored, and update existing tests expected sbom
fixes https://issues.redhat.com/browse/TC-573
> fix: couple of related problems with exhortignore in go.mod

- src/cyclone_dx_sbom.js
- src/providers/python_pip.js
- src/sbom.js
- test/providers/tst_manifests/pip/pip_requirements_txt_ignore/expected_component_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_txt_ignore/expected_stack_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_component_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_stack_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_txt_no_ignore/expected_component_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_txt_no_ignore/expected_stack_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_with_ignore/expected_stack_sbom.json
Remove dummy root component from sbom for python/pip, as in python you don't have a root component, just a list of required packages/modules in requirements.txt
For the purpose, Added new sbom generic feature, to remove from sbom the root component :
1. from components list.
2.  from dependencies list.
3. and from metadata
currently it will be used only by Python/pip.
> fix: remove dummy root component from sbom for python/pip

- .github/workflows/stage.yml
buildah fails to resolve user and password for container registry ( in order to push built image) , because environment variables containing the secrets evaluated globally, and not in staging environment, hence failed to be resolved correctly from staging environment' secrets.
> ci: secrets are only defined in staging environment

- src/analysis.js
- src/providers/python_controller.js
- src/sbom.js
- test/it/end-to-end.js
- test/providers/tst_manifests/npm/package_json_deps_with_exhortignore_object/component_expected_sbom.json
- test/providers/tst_manifests/npm/package_json_deps_without_exhortignore_object/component_expected_sbom.json
fix: potential wrong parsing of pip show with multiline string
When one of the packages contains license key with multi line string value, it can contains the delimiter "---" inside the value ( that separates between the packages in pip show otuput) , hence need to refine the parsing - that is , refine the delimiter.
the problem can be recreated with using in requirements.txt package scipy in python environment >= 3.9.
pip3 show scipy
fixes: https://issues.redhat.com/browse/TC-644
> fix: pip show parsing is incorrect

- src/providers/golang_gomodules.js
- src/providers/python_controller.js
- test/providers/golang_gomodules.test.js
- test/providers/python_pip.test.js
against installed ones
Jira Ticket: https://issues.redhat.com/browse/APPENG-2062
Added functionality of matching manifest versions against installed versions in client environment.
If env var/setting MATCH_MANIFEST_VERSIONS=true, an error will be thrown to user in case installed version of a package has different version than the version written in the manifest.
This functionality was added for python pip' requirements.txt and golang go modules go.mod.
> feat: add functionality of matching manifest versions 

- src/providers/python_controller.js
for virtual environment feature
For cases that EXHORT_PYTHON_VIRTUAL_ENV= true, if the version of a certain package in requirements.txt manifest is not suitable for the client python version, then this might results in error when trying to install.
In order to mitigate it and let the user overcome it , a new flag is introduced, EXHORT_PYTHON_INSTALL_BEST_EFFORTS.
it will be relevant and accessed only for  EXHORT_PYTHON_VIRTUAL_ENV= true, otherwise, it won't even get referenced.
After creating or using the existing virtual environment , the logic will be as follows:
1. if EXHORT_PYTHON_INSTALL_BEST_EFFORTS = false, then old logic will take place, will try to install the requirements.txt as is in the virtual environment , with the declared versions.
2. if EXHORT_PYTHON_INSTALL_BEST_EFFORTS …
> feat: add EXHORT_PYTHON_INSTALL_BEST_EFFORTS functionality

- src/providers/python_controller.js
- src/providers/python_pip.js
> fix: bug with options object propagation in stack and component

- src/providers/python_controller.js
for installed packages
In case a package is not installed in client' python environment, don't try to compare, instead, just skip it and let it throw an error later that package is not installed.
> fix: for python - MATCH_MANIFEST_VERSIONS process only 

- src/providers/python_pip.js
When commenting a package in requirements.txt with `#exhortignore`, if there is a mismatch between versions in pip requirements.txt manifest and environment for a given package, need to remove it from sbom by name only, and not according to version
> fix: python exhortignore - when there is a version mismatch

- src/providers/python_controller.js
In case there is a Cyclic reference in python pip dependency tree , then without detecting it and "cut" the cycle, resolving the dependency tree will never end and the API will enter into infinite loop.
So in every case there is a cycle in the dependency tree, detect it, and cut it.
for example, consider sphinx and sphinxcontrib-applehelp, each one is a dependency of the other , as can seen from the following pip show command of both of packages:
Fix: https://issues.redhat.com/browse/TC-671
> fix: python prevent infinite loop

- src/analysis.js
feat: map providers' user setting to request header for authentication, in case the provider requires basic authentication ( user + token)
> feat: map providers' user setting to request header for authentication

- src/providers/java_maven.js
Sometimes XML parser parse from maven pom.xml ( effective or real pom) a full major version ( for example 1 or 2 or 3), as number instead of string, hence causing exceptions when creating purls.
on such cases, need to "stringify" the number before creating the purl.
> fix: maven - in case version is of type `number` , "stringify" it

- src/providers/java_maven.js
- test/providers/java_maven.test.js
Fixes: https://issues.redhat.com/browse/TC-787
> fix: maven sa wrongly excluding provided scoped artifacts

- .github/workflows/stage.yml
- src/providers/python_controller.js
- test/it/end-to-end.js
For CI/CD pipelines, it's a lot of times better to install requirements.txt manifest in a dedicated agent/slave/computer/container that contains the desired  python & pip versions, and invoke the rhda analysis in different agent/slave/computer/container ( let's denote it as "node") -  that contains the whole infrastructure required to invoke the analysis alone ( including python and pip binaries, but the problem is that it "stuck" with a given versions of python and pip in this node, hence very limited to the versions of packages in requirements.txt).
For that purpose, and in such cases that we need to separate the analysis and the pip install in different steps/stages and even on different nodes, this PR introduces two environment variables, these two env variables will need to be …
> feat: get output of pip commands from env variables

- src/cli.js
Recent api changes in exhort backend change the summary option of the stack analysis command in the exhort cli.
Fixes [JIRA-2321](https://issues.redhat.com/browse/APPENG-2321)
> fix: fix broken cli stack analysis summary option

- src/cli.js
- src/providers/java_maven.js
- src/providers/javascript_npm.js
- test/it/end-to-end.js
> fix: fix missing version/namespace in maven & npm

- src/cli.js
By setting `.wrap(null)`  a terminal output will wrap without a column limit, ensuring optimal readability on terminals of any width.
The issue with line wrapping
[Source](https://yargs.js.org/docs/#api-reference-wrapcolumns)
> fix: unlimited wrapping for a terminal output

- src/analysis.js
- src/providers/python_controller.js
- src/providers/python_pip.js
- test/providers/python_pip.test.js
Because of a performance issue with native pip show command , starting from python version 3.11.X, introduced an alternate flow of using pipdeptree python utility , instead of pip freeze --all + pip show list_of_deps as a source of data for building the dependency tree of python ( the algorithm remain the same anyway).
**Related issue (if any):** fixes [JIRA APPENG-2154](https://issues.redhat.com/browse/APPENG-2154)
The new logic will be controlled by a new setting (env var/property) - `EXHORT_PIP_USE_DEP_TREE`, if it will be set to true, it will use the pipdeptree as the source to build the dependency tree, otherwise, it will use native pip commands pip freeze + show. default is EXHORT_PIP_USE_DEP_TREE=false.
> feat: fix performance issue in python version >= 3.11.X

- src/analysis.js
> fix: expose exhort backend errors to clients

- src/providers/java_gradle.js
- test/it/test_manifests/gradle/build.gradle
For gradle component analysis, if in manifest an artifact is specified twice, once with version and second time without version, then it's generated like that in the sbom , which is a duplicate ( the fix filtering out the artifact that doesn't contain version)
build.gradle: 
```gradle
dependencies {
implementation "log4j:log4j:1.2.17"
implementation group: 'log4j', name: 'log4j'
}
```
generated sbom
```json
{
{
"group": "log4j",
"name": "log4j",
"version": "1.2.17",
"purl": "pkg:maven/log4j/log4j@1.2.17",
"type": "library",
"bom-ref": "pkg:maven/log4j/log4j@1.2.17"
},
{
"group": "log4j",
"name": "log4j",
"purl": "pkg:maven/log4j/log4j",
"type": "library",
"bom-ref": "pkg:maven/log4j/log4j"
}
}
```
the generated sbom for component analysis should only contain the log4j with the version, …
> fix: gradle component analsyis duplicates artifacts in sbom

- src/providers/java_gradle.js
> fix: gradle - fix crash and remove dep without ver from sbom

- package-lock.json
- package.json
- src/index.js
- test/it/end-to-end.js
1. Fix IT test for the case of empty Exhort responses
2.  downgrade cyclonedx-lib version to previous minor version, in order to overcome vulnerability with high severity
> fix: vulnerability in 3rd party package and fixed breakage of IT tests

- .github/workflows/stage.yml
Add re-test functionality to staging workflow - using [re-test github action](https://github.com/zvigrinberg/git-retest-checkup-action)
In case head branch ( feature/topic/hotfix - whichever  ) forked from the base branch, and before merging it back, base branch commits tree advanced with additional commits ( merged from different branches or pushed directly - whichever ), in such case, if the head branch is not rebased on top of the base branch, there is a chance ( not big chance but still) that tests that were passed on PR workflow will fail after head branch will be merged to base, in this case, i want to identify such situations during the staging workflow, but still, i don't want to run all the time tests before publishing the npm package, but i want to identify if a re-test is …
> ci: add re-test functionality to staging workflow

- src/index.js
> fix: commonjs clients crash

- package-lock.json
- package.json
Up until now, node-fetch lib was fetched via the dev-dependency `open-api-generator` ( which obviously this package  and its transitives are  not inherited by clients of this api)
ever since we changed the cyclone-dx library version ( that by chance included node-fetch lib as well) - we started to experience errors in component analysis in clients ( rhda vscode extension and rhda lsp server) that it can't find node-fetch library.
**Related issue (if any):** fixes [TC-1400](https://issues.redhat.com/browse/TC-1400)
> fix: add node-fetch to dependencies

- src/analysis.js
- src/cyclone_dx_sbom.js
- src/index.js
- src/providers/golang_gomodules.js
- src/providers/java_gradle.js
- src/providers/java_maven.js
- src/providers/javascript_npm.js
- src/providers/python_pip.js
- src/sbom.js
In order to ease troubleshooting and boost recreation of  issues in order to solve them, adding manifest content into sbom metadata field in the sbom json , that is,  create two new fields under sbom->metadata.properties -> `rhda:manifest:content` and `rhda:manifest:filename`
```json
{
"bomFormat": "CycloneDX",
"specVersion": "1.4",
"version": 1,
"metadata": {
"timestamp": "2024-06-13T11:00:18.855Z",
"component": {
"group": "example.com",
"name": "software",
"version": "v0.0.0",
"purl": "pkg:golang/example.com/software@v0.0.0",
"type": "application",
"bom-ref": "pkg:golang/example.com/software@v0.0.0"
},
"properties": [
{
"name": "rhda:manifest:content",
"value": "bW9kdWxlIGV4YW1wbGUuY29tL3NvZnR3YXJlCgoKZ28gMS4yMi40ICAgICAgICAgICAgICAgICAgICAgICAgICAKCgoKCgo="
},
{
"name": …
```
> feat: add manifest content to sbom' metadata

- src/providers/golang_gomodules.js
- src/providers/java_gradle.js
- src/providers/java_maven.js
- src/providers/javascript_npm.js
- src/providers/python_controller.js
- src/providers/python_pip.js
> fix: handle spaces in package manager binaries paths

- src/analysis.js
- src/providers/java_gradle.js
- test/providers/tst_manifests/gradle/deps_with_ignore_notations/expected_component_sbom.json
- test/providers/tst_manifests/gradle/deps_with_no_ignore_common_paths/expected_component_sbom.json
> fix: add and fix missing configurations for gradle ca

- src/providers/java_maven.js
- test/it/end-to-end.js
- test/providers/tst_manifests/maven/pom_with_multiple_modules/component_analysis_expected_sbom.json
In maven  Component analysis , we're using xml-fast-parser in order to retrieve direct dependencies from pom.xml
in case there is a string version in the format of "x.0" ( x is an integer, x >=0 ) , then by default it omits the ".0" and convert it number as integer - x.
We need to configure xml fast parser to ignore such cases, so it will let the string become as is in case of format x.0 ( for every natural integer x >= 0).
> fix: maven component analysis xml wrong parsing of x.0 versions ( x >=0)

- src/providers/javascript_npm.js
- src/providers/python_controller.js
> fix: bugs of windows os for python and npm ecosystems

- src/providers/base_java.js
- src/providers/java_gradle.js
1. Fix https://issues.redhat.com/browse/TC-1706 - a bug in which only `api` and `implementation` gradle configuration types are respected for //exhortignore
2. Fix https://issues.redhat.com/browse/TC-1707 - a bug in which `import` scope is not included in stack analysis.
> fix: 2 bugs of gradle and maven

- .github/auto-me-bot.yml
The Bot that verifies commits are signed off keeps failing although I verified all commits are correctly signed.
Disabling this check will allow us to keep maintaining this repository.
Potentially we can replace this with something like https://probot.github.io/apps/dco/
> ci: disable auto-me-bot signed off verification

- .github/workflows/oapi_spec.yaml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stage.yml
Currently the tests for new PRs will always fail due to usage of old github actions. I currently see these errors:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
This PR should make sure our CI goes back to just work.
> ci: upgrade github action dependencies

- package-lock.json
- package.json
- src/providers/base_java.js
- src/providers/java_gradle.js
- src/providers/java_maven.js
- src/tools.js
- test/it/end-to-end.js
- test/providers/java_gradle_groovy.test.js
- test/providers/java_gradle_kotlin.test.js
- test/providers/java_maven.test.js
`execSync` was being passed a callback in order to return a custom error message, which isnt actually supported by `execSync`. Extended this to support more granular checking & reporting of errors.
This PR also changes how maven commands were invoked. Instead of building strings to pass to the shell, it invokes the passed maven binary directly and passes args via array to avoid having to do shell escaping. 
**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/163
> fix: correctly return custom maven invocation error messages

- src/providers/javascript_npm.js
An npm object a null/unset `dependencies` key will throw an error later when attempting to interact with it if the npm package defines no dependencies
Related issues (if any): #162 
> fix: error when attempting to generate sbom for npm package with no dependencies

- src/providers/python_controller.js
- test/it/test_manifests/pip/requirements.txt
We read requirements.txt in (at least) 2 places to parse the lines for dependencies to resolve. We are meant to ignore comments but in one section we were not removing leading whitespace before checking for the presence of the comment token `#`
**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/167
- fixes: https://github.com/trustification/exhort-javascript-api/issues/167
> fix: bug in handling of comments with leading whitespace in requirements.txt

- README.md
- docker-image/scripts/rhda.sh
- integration/run_its.sh
- integration/testers/javascript/index.js
- integration/testers/typescript/index.ts
- src/analysis.js
- src/cli.js
- src/index.js
- src/providers/golang_gomodules.js
- src/providers/java_gradle.js
- src/providers/java_maven.js
- src/providers/javascript_npm.js
- src/providers/python_pip.js
- src/tools.js
- test/it/end-to-end.js
- test/providers/golang_gomodules.test.js
- test/providers/java_gradle_groovy.test.js
- test/providers/java_gradle_kotlin.test.js
- test/providers/java_maven.test.js
- test/providers/javascript_npm.test.js
- test/providers/python_pip.test.js
Updates the API for the `componentAnalysis` entrypoint to match changes made to the component analysis entrypoint in the Java API (see linked issue below). Component analysis now always operates off the manifest path (as the gradle analysis provider already did) instead of manifest content, same as stack analysis.
Note: This is a breaking change to the API.
**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/166
> feat: update component analysis API to work with manifest path instead of manifest content

- integration/run_its.sh
- src/providers/java_maven.js
- src/tools.js
Adds support for using [mvnw](https://maven.apache.org/wrapper/) instead of maven from PATH/EXHORT_MVN_PATH. If set, mvnw is searched for starting in the directory the passed manifest is in, traversing upwards until either the git repo root is hit, or the root of the drive. 
The `EXHORT_PREFER_MVNW` env var controls this preference.
**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/169
> feat: support mvnw if requested and exists

- .github/workflows/stage.yml
Due to `npm error 403 403 Forbidden - PUT https://npm.pkg.github.com/@trustification%2fexhort-javascript-api - Permission permission_denied: create_package` when attempting to publish on a recent main commit. Confirmed that `secrets.GITHUB_TOKEN` should have permissions according to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository
> chore: use secrets.GITHUB_TOKEN for npm publish & creating GH release

- docker-image/Dockerfiles/Dockerfile
It seems even though this repo was migrated from RHEcosystemAppEng org to trustification, packages published while in the old org can't be referenced with the new orgs namespace. So we'll have to keep it for this section where we reference an old version. Speaking of, why does this reference a hard-coded old version instead of tracking main? :thinking: 
> chore: revert to RHEcosystemAppEng for installing exhort-javascript-api in docker image

- .github/workflows/pr.yml
- .github/workflows/stage.yml
Use the github built-in condition for setting up Python and re-running the tests
> build: migrate deprecated action and remove pip cache

- .github/workflows/release.yml
- .github/workflows/stage.yml
- docker-image/Dockerfiles/Dockerfile
- docker-image/configs/.npmrc
**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/176
- fixes: https://github.com/trustification/exhort-javascript-api/issues/176
> build: update dockerfile to use provided exhort-javascript-api instead of hardcoded version

- src/providers/base_java.js
- src/providers/java_gradle.js
- src/providers/java_maven.js
- src/tools.js
This shouldve been done this way originally (by me), relatively quick change so Im doing it now 
> chore: dont pass callback for thrown errors in invokeCommand

- src/providers/python_controller.js
- src/providers/python_pip.js
- src/tools.js
- test/providers/python_pip.test.js
- test/providers/tst_manifests/pip/pip_requirements_txt_ignore/expected_component_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_txt_ignore/expected_stack_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_txt_ignore/requirements.txt
- test/providers/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_component_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_txt_no_ignore/expected_stack_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_txt_no_ignore/requirements.txt
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_txt_no_ignore/expected_component_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_txt_no_ignore/expected_stack_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_txt_no_ignore/requirements.txt
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_with_ignore/expected_component_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_with_ignore/expected_stack_sbom.json
- test/providers/tst_manifests/pip/pip_requirements_virtual_env_with_ignore/requirements.txt
Last of the set once https://github.com/trustification/exhort-javascript-api/pull/182 is merged!
**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/163
> fix: correctly return custom python invocation error messages

- package.json
- src/index.js
- src/providers/javascript_npm.js
Also added type signature overloads for stack analysis function to narrow the return type based on if HTML report is requested or not
> fix: use --prefix instead of --dir for npm provider

- src/providers/golang_gomodules.js
**Related issues (if any):** https://github.com/trustification/exhort-javascript-api/issues/184#issuecomment-2829592456
- fixes: https://github.com/trustification/exhort-javascript-api/issues/184#issuecomment-2829592456
> fix: ignore reference to 'go@version' from newer `go mod graph` output

- src/providers/javascript_npm.js
The `--prefix` flag is known to not work on windows. The original fix for this was to `os.chdir` to the path, perform install operation, and then reset cwd. This worked but had a side effect of adding a self-reference to the package.json. By removing the `--prefix` flag entirely on windows, the problem is addressed for some reason
- fixes: 
https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/731
https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/732
https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/738
https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/739
> fix: address self-adding of npm workspace to package.json

- src/providers/java_maven.js
If mvnw is preferred but not found, we should be falling back to check for global maven installation instead of continuing on as if everythings okay
- fixes: https://github.com/trustification/exhort-javascript-api/issues/192
> fix: fallback to global mvn if mvnw not found

- .gitignore
- README.md
- src/analysis.js
- test/analysis.test.js
Introduce the configuration property `EXHORT_PROXY_URL` that will be used in any `fetch` operation
Fix #196
> feat: support configure a proxy url

- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stage.yml
It updates when a release can be triggered and allows to create `ea` versions for release branches as well.
Allowing multiple development versions: `0.2.1-ea.3` and `0.1.1-ea.74`
Also the release workflow will be manually triggered only.
> chore(ci): update workflow triggers for releases

- src/providers/processors/yarn_berry_processor.js
Yarn Berry on Windows platform returns Linux EOL output. This fix ensures all outputs are normalized.
- fixes: #179
> fix: normalize yarn berry output parsing

- src/providers/java_maven.js
- test/providers/java_maven.test.js
- test/providers/tst_manifests/maven/pom_deps_with_ignore_version_from_property/component_analysis_expected_sbom.json
- test/providers/tst_manifests/maven/pom_deps_with_ignore_version_from_property/effective-pom.xml
- test/providers/tst_manifests/maven/pom_deps_with_ignore_version_from_property/mvn_deptree.txt
- test/providers/tst_manifests/maven/pom_deps_with_ignore_version_from_property/pom.xml
- test/providers/tst_manifests/maven/pom_deps_with_ignore_version_from_property/stack_analysis_expected_sbom.json
- test/providers/tst_manifests/maven/pom_with_multiple_modules/component_analysis_expected_sbom.json
- test/providers/tst_manifests/maven/pom_with_multiple_modules/module4/pom.xml
Fix a parsing problem affecting some Maven versions that are parsed as numbers
- fixes: https://github.com/trustification/exhort-javascript-api/issues/220
> fix: don't parse any value as number

- package-lock.json
- package.json
- src/providers/base_java.js
- test/providers/java_maven.test.js
- test/providers/tst_manifests/maven/pom_with_mvn_wrapper/.mvn/wrapper/maven-wrapper.properties
- test/providers/tst_manifests/maven/pom_with_mvn_wrapper/mvnw
- test/providers/tst_manifests/maven/pom_with_mvn_wrapper/mvnw.cmd
- test/providers/tst_manifests/maven/pom_with_mvn_wrapper/pom.xml
`toolPath` can be an absolute path to mvn/gradle, which would result in checking for `EXHORT_/usr/bin/mvn_PATH` instead of `EXHORT_MVN_PATH` for a user-provided path.
**Related issues (if any):** https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/779
> fix: use global binary name to select env var to use instead of provided mvn/gradle path

- .esmockrc.js
- .mocharc.json
- package.json
- src/cyclone_dx_sbom.js
- src/providers/java_gradle.js
- src/sbom.js
- test/providers/java_gradle_groovy.test.js
- test/providers/java_gradle_kotlin.test.js
- test/providers/java_maven.test.js
- test/providers/javascript.test.js
- test/providers/tst_manifests/gradle/deps_with_ignore_full_specification/expected_component_sbom.json
- test/providers/tst_manifests/gradle/deps_with_ignore_full_specification/expected_stack_sbom.json
- test/providers/tst_manifests/gradle/deps_with_ignore_named_params/build.gradle
- test/providers/tst_manifests/gradle/deps_with_ignore_named_params/expected_component_sbom.json
- test/providers/tst_manifests/gradle/deps_with_ignore_named_params/expected_stack_sbom.json
- test/providers/tst_manifests/gradle/deps_with_ignore_notations/expected_component_sbom.json
- test/providers/tst_manifests/gradle/deps_with_ignore_notations/expected_stack_sbom.json
- test/providers/tst_manifests/gradle/deps_with_no_ignore_common_paths/expected_component_sbom.json
- test/providers/tst_manifests/gradle/deps_with_no_ignore_common_paths/expected_stack_sbom.json
- test/providers/tst_manifests/js-common/package_json_deps_without_exhortignore_object/component_expected_sbom.json
- test/providers/tst_manifests/yarn-berry/package_json_deps_without_exhortignore_object/stack_expected_sbom.json
- test/providers/tst_manifests/yarn-classic/package_json_deps_with_exhortignore_object/stack_expected_sbom.json
- test/providers/tst_manifests/yarn-classic/package_json_deps_without_exhortignore_object/stack_expected_sbom.json
- test/utils/sbom_utils.js
Refactor how the Gradle dependencies are resolved because as the full tree is available in both component and stack analysis we can use the right trees instead of just the `api / implementation` listings. This helps resolving the correct versions.
With that it is also possible to include the correct scope (required / optional) to the sbom
- fixes: #226 
- fixes: #227 
- fixes #228 
Also includes a fix for running the unit tests.
> fix: problem with gradle and yarn version resolution

- .github/workflows/pr.yml
- package-lock.json
- package.json
- src/analysis.js
- src/oci_image/images.js
- src/oci_image/utils.js
- src/tools.js
- test/providers/tst_manifests/image/httpd:2.4.49.json
- test/providers/tst_manifests/image/httpd:2.4.49^^amd64.json
- test/providers/tst_manifests/image/httpd@sha256:4b5cb7697fea2aa6d398504c381b693a54ae9ad5e6317fcdbb7a2d9b8c3b1364.json
image analysis was still using `process.env` in a lot of places such as for using EXHORT_IMAGE_PLATFORM. This is a holdover from when this was still the externally executed JAR file, where reading from env was the correct approach. This PR updates this translated code to use `getCustom` like other parts of the library, and passing `opts` down correctly to all the relevant sections
- fixes: https://issues.redhat.com/browse/TC-2797
> fix: use & pass down opts for getCustom in imageAnalysis

- src/providers/golang_gomodules.js
- test/providers/golang_gomodules.test.js
- test/providers/tst_manifests/golang/go_mod_empty/expected_sbom_component_analysis.json
- test/providers/tst_manifests/golang/go_mod_empty/expected_sbom_stack_analysis.json
- test/providers/tst_manifests/golang/go_mod_empty/go.mod
If go.mod file is empty `go mod graph` would return only one line (containing `@go` that we filter out), which would cause an exception when trying to determine the root module. Instead we can use `go mod edit -json` to get the root module from the following output:
```json
{
"Module": {
"Path": "github.com/sample/empty-module"
},
"Go": "1.24",
"Require": null,
"Exclude": null,
"Replace": null,
"Retract": null,
"Tool": null
}
```
> fix: properly handle go.mod files with no dependencies

- src/providers/python_pip.js
When the python packages does not define a version the stack analysis returns a confusing error:
```
Error: Invalid purl: "name" is a required field.
```
It should allow parsing lines without version because they default to the latest version.
- fixes: [TC-2802](https://issues.redhat.com/browse/TC-2802)
> fix: allow ignored packages without version

- src/oci_image/utils.js
`hostInfo` returns an empty string if the string isnt found in `docker/podman info`. `??` won't fallback to checking with podman as this operates on nullables, not truthiness
> fix: correctly fallback to podman if docker hostinfo returns nothing
